export { ReactComponent as SadFace } from "./images/sad-face.svg"
export { ReactComponent as BackIcon } from "./images/back.svg"
export { ReactComponent as SearchIcon } from "./images/search.svg"
export { ReactComponent as EyeIcon } from "./images/eye.svg"
export { ReactComponent as EditIcon } from "./images/edit.svg"
